### ISSUE TITLE
Java console app doesn't support key listener

### ISSUE THREAD

**Issue by ktarou** [Mitrais/java-bootcamp-working#3]
In Fund Transfer Screen 

> Please enter destination account and press enter to continue or 
press cancel (Esc) to go back to Transaction: 

What if we change to "blank input will display transaction screen" ?

**Comment by jchacana** [comment]
Yep, sounds better just to check for empty input

**Comment by jchacana** [comment]
@ktarou Look at this thread https://stackoverflow.com/questions/4608854/in-java-what-is-the-best-way-to-capture-a-tab-keystroke/4609067#4609067 where it says there's a way of capturing the keystroke, but by using another library which goes way beyond scope

I was just trying to finish this and hit this problem:

` Please enter reference number (Optional) and 
press enter to continue or 
press cancel (Esc) to go back to Transaction: `

As the reference number is optional, it can be blank, but we were going to treat blank as Esc key, so here we are on a dead-end. Maybe we should change the Esc key for the word "ESC", or just enter a 0 number. Because blank in this screen is perfectly valid

**Comment by ktarou** [comment]
I think we can skip the reference number here.
@jchacana what do you think?

**Comment by jchacana** [comment]
Sure, I think it's better. But instead, I would add a "transaction number generator" (random) when a transaction gets approved. What do you think?

**Comment by ktarou** [comment]
Interesting, could you update the wiki?

**Comment by jchacana** [comment]
Yes, I updated the wiki and pushed new changes to the pull request. I will push one more change later, related to the use of the reference number, for now it's still pending but I think we can close this issue

**Comment by ktarou** [comment]
Thanks
